wireguard_endpoint: "{{ ansible_host }}"
wireguard_port: 51822
wireguard_private_key: "{{ wireguard_internet_gateway_private_key }}"
wireguard_allowed_ips: "0.0.0.0/0, ::/0"
wireguard_addresses:
  - "{{ wireguard_network_ranges | ansible.utils.ipaddr('2') | ansible.utils.ipaddr('address') | ansible.utils.ipaddr('host') | join(', ') }}"
wireguard_preup:
  # IPv4 forwarding
  - sysctl -w net.ipv4.ip_forward=1
  # IPv4 masquerading
  - iptables -t mangle -A PREROUTING -i wg0 -j MARK --set-mark 0x30
  - iptables -t nat -A POSTROUTING ! -o wg0 -m mark --mark 0x30 -j MASQUERADE
  # IPv6 forwarding
  - sysctl -w net.ipv6.conf.all.forwarding=1
  # IPv6 masquerading
  - ip6tables -t mangle -A PREROUTING -i wg0 -j MARK --set-mark 0x30
  - ip6tables -t nat -A POSTROUTING ! -o wg0 -m mark --mark 0x30 -j MASQUERADE
wireguard_postdown:
  - iptables -t mangle -D PREROUTING -i wg0 -j MARK --set-mark 0x30
  - iptables -t nat -D POSTROUTING ! -o wg0 -m mark --mark 0x30 -j MASQUERADE
  - ip6tables -t mangle -D PREROUTING -i wg0 -j MARK --set-mark 0x30
  - ip6tables -t nat -D POSTROUTING ! -o wg0 -m mark --mark 0x30 -j MASQUERADE

wireguard_unmanaged_peers: {}
